services:
  surrealdb:
    build:
      context: .
      dockerfile: surrealdb.Dockerfile
    container_name: surrealdb
    ports:
      - ${SURREALDB_PORT}:${SURREALDB_PORT}
    entrypoint:
      - "/surreal"
      - "start"
      - "--user"
      - "${AUTH_SURREALDB_USERNAME}"
      - "--pass"
      - "${AUTH_SURREALDB_PASSWORD}"
      - "memory"
      - "--import-file"
      - "init.surql"

  service:
    build:
      context: ./service
    container_name: mcp-service
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - surrealdb
    env_file:
      - .env
    entrypoint:
      - "npm"
      - "run"
      - "preview"

  calculator:
    build:
      context: ./calculator
      dockerfile: Dockerfile
    ports:
      - ${CALCULATOR_PORT}:${CALCULATOR_PORT}
    env_file:
      - .env
    entrypoint:
      - "npm"
      - "run"
      - "preview"
